name: Create and Setup Repository

on:
  workflow_dispatch: # This allows the workflow to be manually triggered

jobs:
  create-repo:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    env:
      REPO_NAME: kuks-repo # Set the repository name here
      ORG_NAME: Tronixjenkins

    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.GHAPPID }}
          private-key: ${{ secrets.GH_APPID }}

      - name: Use the token
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          
      - name: Checkout the current repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Create a new repository
        id: create_repo
        run: |
          response=$(curl -s -o response.json -w "%{http_code}" -X POST \
            -H "Authorization: token ${{ env.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/orgs/${{ env.ORG_NAME }}/repos \
            -d "{\"name\":\"${{ env.REPO_NAME }}\",\"private\":false}")
          echo "HTTP Status Code: $response"
          echo "Response JSON:"
          cat response.json
          if [ "$response" -ne 201 ]; then
            echo "Failed to create repository"
            exit 1
          fi
          

      - name: Clone the new repository
        run: |
          git clone https://${{ env.GH_TOKEN }}@github.com/${{ env.ORG_NAME }}/${{ env.REPO_NAME }}.git
          cd ${{ env.REPO_NAME }}
          echo "# ${{ env.REPO_NAME }}" > README.md
          git add README.md
          git commit -m "Initial commit"
          git push https://${{ env.GH_TOKEN }}@github.com/${{ env.ORG_NAME }}/${{ env.REPO_NAME }}.git

      - name: Clone the source repository to copy the CI/CD workflow
        run: |
          git clone https://${{ env.GH_TOKEN }}@github.com/${{ env.ORG_NAME }}/test-copy.git

      - name: Copy CI/CD workflow from test_copy to the new repository
        run: |
          cd test-copy
          mkdir -p ../${{ env.REPO_NAME }}/.github/workflows
          cp .github/workflows/blank.yml ../${{ env.REPO_NAME }}/.github/workflows/
          cd ../${{ env.REPO_NAME }}
          git add .github/workflows/blank.yml
          git commit -m "Add CI/CD workflow from test_copy"
          git push origin main

      - name: Create develop branch from main
        run: |
          cd ${{ env.REPO_NAME }}
          git checkout -b develop
          git push --set-upstream https://${{ env.GH_TOKEN }}@github.com/${{ env.ORG_NAME }}/${{ env.REPO_NAME }}.git develop

      - name: Create qat branch from develop
        run: |
          cd ${{ env.REPO_NAME }}
          git checkout develop
          git checkout -b qat
          git push --set-upstream https://${{ env.GH_TOKEN }}@github.com/${{ env.ORG_NAME }}/${{ env.REPO_NAME }}.git qat

      - name: Create prd branch from qat
        run: |
          cd ${{ env.REPO_NAME }}
          git checkout qat
          git checkout -b prd
          git push --set-upstream https://${{ env.GH_TOKEN }}@github.com/${{ env.ORG_NAME }}/${{ env.REPO_NAME }}.git prd
