name: Create and Setup Repository

on:
  workflow_dispatch: # This allows the workflow to be manually triggered

jobs:
  create-repo:
    runs-on: ubuntu-latest

    env:
      REPO_NAME: new-repo2  # Set the repository name here
      ORG_NAME: Tronixjenkins

    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          
      - name: Create a new repository
        id: create_repo
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/orgs/${{ env.ORG_NAME }}/repos \
            -d "{\"name\":\"${{ env.REPO_NAME }}\",\"private\":false}"

      - name: Clone the new repository
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git clone https://${{ secrets.GH_PAT }}@github.com/${{ env.ORG_NAME }}/${{ env.REPO_NAME }}.git
          cd ${{ env.REPO_NAME }}
          echo "# ${{ env.REPO_NAME }}" > README.md
          git add README.md
          git commit -m "Initial commit"
          git push https://${{ secrets.GH_PAT }}@github.com/${{ env.ORG_NAME }}/${{ env.REPO_NAME }}.git
     
      - name: Create develop branch from main
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          cd ${{ env.REPO_NAME }}
          git checkout -b develop
          git push --set-upstream https://${{ secrets.GH_PAT }}@github.com/${{ env.ORG_NAME }}/${{ env.REPO_NAME }}.git develop

      - name: Create qat branch from develop
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          cd ${{ env.REPO_NAME }}
          git checkout develop
          git checkout -b qat
          git push --set-upstream https://${{ secrets.GH_PAT }}@github.com/${{ env.ORG_NAME }}/${{ env.REPO_NAME }}.git qat

      - name: Create prd branch from qat
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          cd ${{ env.REPO_NAME }}
          git checkout qat
          git checkout -b prd
          git push --set-upstream https://${{ secrets.GH_PAT }}@github.com/${{ env.ORG_NAME }}/${{ env.REPO_NAME }}.git prd
          
      - name: Copy CI/CD workflow from dbtrepo to the new repository
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          mkdir -p ${{ env.REPO_NAME }}/.github/workflows
          cp ${{ env.REPO_NAME }}/test-copy/.github/workflows/blank.yml ${{ env.REPO_NAME }}/.github/workflows/
          cd ${{ env.REPO_NAME }}
          git add .github/workflows/blank.yml
          git commit -m "Add CI/CD workflow from dbtrepo"
          git push https://${{ secrets.GH_PAT }}@github.com/${{ env.ORG_NAME }}/${{ env.REPO_NAME }}.git
