name: Create and Setup Repository

on:
  workflow_dispatch: # This allows the workflow to be manually triggered

jobs:
  create-repo:
    runs-on: ubuntu-latest

    env:
      REPO_NAME: new-test-repo # Set the repository name here
      ORG_NAME: Tronixjenkins

    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Create a new repository
        id: create_repo
        run: |
          response=$(curl -s -o response.json -w "%{http_code}" -X POST \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/orgs/${{ env.ORG_NAME }}/repos \
            -d "{\"name\":\"${{ env.REPO_NAME }}\",\"private\":false}")
          if [ "$response" -ne 201 ]; then
            echo "Failed to create repository"
            cat response.json
            exit 1
          fi

      - name: Clone the new repository
        if: steps.check_repo.outputs.repo_exists == 'false'
        run: |
          git clone https://${{ secrets.GH_PAT }}@github.com/${{ env.ORG_NAME }}/${{ env.REPO_NAME }}.git
          cd ${{ env.REPO_NAME }}
          echo "# ${{ env.REPO_NAME }}" > README.md
          git add README.md
          git commit -m "Initial commit"
          git push origin main

      - name: Clone the source repository to copy the CI/CD workflow
        run: |
          git clone https://${{ secrets.GH_PAT }}@github.com/${{ env.ORG_NAME }}/test_copy.git

      - name: Copy CI/CD workflow from test_copy to the new repository
        run: |
          mkdir -p ${{ env.REPO_NAME }}/.github/workflows
          cp test_copy/.github/workflows/blank.yml ${{ env.REPO_NAME }}/.github/workflows/
          cd ${{ env.REPO_NAME }}
          git add .github/workflows/blank.yml
          git commit -m "Add CI/CD workflow from test_copy"
          git push origin main

      - name: Create develop branch from main
        run: |
          cd ${{ env.REPO_NAME }}
          git checkout -b develop
          git push --set-upstream origin develop

      - name: Create qat branch from develop
        run: |
          cd ${{ env.REPO_NAME }}
          git checkout develop
          git checkout -b qat
          git push --set-upstream origin qat

      - name: Create prd branch from qat
        run: |
          cd ${{ env.REPO_NAME }}
          git checkout qat
          git checkout -b prd
          git push --set-upstream origin prd
      #     git commit -m "Add CI/CD workflow from test_copy"
      #     git push origin main
