name: Create and Setup Repository

on:
  workflow_dispatch: # This allows the workflow to be manually triggered

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v2

      - name: Create a new repository
        id: create_repo
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/user/repos \
            -d '{"name":"Test_repo","private":false}'

      - name: Clone the new repository
        run: |
          git clone https://github.com/${{ github.repository_owner }}/Test_repo.git
          cd Test_repo
          echo "# New Repo" > README.md
          git add README.md
          git commit -m "Initial commit"
          git push https://github.com/${{ github.repository_owner }}/Test_repo.git



      - name: Create develop branch from main
        run: |
          cd Test_repo
          git checkout -b develop
          git push --set-upstream https://github.com/${{ github.repository_owner }}/Test_repo.git develop

      - name: Create qat branch from develop
        run: |
          cd Test_repo
          git checkout develop
          git checkout -b qat
          git push --set-upstream https://github.com/${{ github.repository_owner }}/Test_repo.git qat

      - name: Create prd branch from qat
        run: |
          cd Test_repo
          git checkout qat
          git checkout -b prd
          git push --set-upstream https://github.com/${{ github.repository_owner }}/Test_repo.git prd

      # - name: Copy CI/CD workflow to the new repository
      #   run: |
      #     cd Test_repo
      #     mkdir -p .github/workflows
      #     cp ../.github/workflows/example-workflow.yml .github/workflows/
      #     git add .github/workflows/example-workflow.yml
      #     git commit -m "Add CI/CD workflow"
      #     git push https://github.com/${{ github.repository_owner }}/Test_repo.git

      
